import type * as Monaco from 'monaco-editor/esm/vs/editor/editor.api.js'
import { editorTheme } from './controller'

export const monacoThemeName = 'qua-editor'

/** Call only after Monaco's first create() has installed service overrides. */
export function connectMonacoTheme(monaco: typeof Monaco): () => void {
  const apply = () => {
    const color = (name: string) => editorTheme.color(name)
    monaco.editor.defineTheme(monacoThemeName, {
      base: editorTheme.mode === 'dark' ? 'vs-dark' : 'vs',
      inherit: true,
      rules: [
        { token: '', foreground: color('text') },
        { token: 'comment', foreground: color('comment') },
        { token: 'keyword', foreground: color('keyword') },
        { token: 'string', foreground: color('string') },
        { token: 'number', foreground: color('number') },
        { token: 'type', foreground: color('type') },
        { token: 'type.identifier', foreground: color('type') },
        { token: 'annotation', foreground: color('function') },
        { token: 'predefined', foreground: color('function') },
        { token: 'tag', foreground: color('keyword') },
        { token: 'attribute.name', foreground: color('function') },
        { token: 'delimiter', foreground: color('muted') },
      ],
      colors: {
        'focusBorder': color('accent'),
        'foreground': color('text'),
        'descriptionForeground': color('muted'),
        'errorForeground': color('danger'),
        'editor.background': color('code-bg'),
        'editor.foreground': color('text'),
        'editorLineNumber.foreground': color('line-number'),
        'editorLineNumber.activeForeground': color('accent'),
        'editorCursor.foreground': color('accent'),
        'editor.lineHighlightBackground': color('line-highlight'),
        'editor.selectionBackground': color('selection'),
        'editor.inactiveSelectionBackground': color('accent-bg'),
        'editor.selectionHighlightBackground': `${color('accent')}25`,
        'editor.findMatchBackground': color('selection'),
        'editor.findMatchBorder': color('accent'),
        'editor.findMatchHighlightBackground': `${color('accent')}20`,
        'editorIndentGuide.background1': color('divider'),
        'editorIndentGuide.activeBackground1': color('border'),
        'editorWhitespace.foreground': color('border'),
        'editorError.foreground': color('danger'),
        'editorWarning.foreground': color('warning'),
        'editorInfo.foreground': color('info'),
        'editorGutter.background': color('code-bg'),
        'editorWidget.background': color('raised'),
        'editorWidget.foreground': color('text'),
        'editorWidget.border': color('border'),
        'editorHoverWidget.background': color('raised'),
        'editorHoverWidget.foreground': color('text'),
        'editorHoverWidget.border': color('border'),
        'editorSuggestWidget.background': color('raised'),
        'editorSuggestWidget.foreground': color('text'),
        'editorSuggestWidget.border': color('border'),
        'editorSuggestWidget.selectedBackground': color('selection'),
        'editorSuggestWidget.highlightForeground': color('accent'),
        'input.background': color('input-bg'),
        'input.foreground': color('text'),
        'input.border': color('border'),
        'input.placeholderForeground': color('placeholder'),
        'list.activeSelectionBackground': color('selection'),
        'list.activeSelectionForeground': color('text'),
        'list.hoverBackground': color('hover'),
        'list.focusHighlightForeground': color('accent'),
        'list.highlightForeground': color('accent'),
        'menu.background': color('raised'),
        'menu.foreground': color('text'),
        'menu.selectionBackground': color('selection'),
        'menu.selectionForeground': color('text'),
        'menu.separatorBackground': color('divider'),
        'peekView.border': color('border'),
        'peekViewTitle.background': color('raised'),
        'peekViewTitleLabel.foreground': color('text'),
        'peekViewTitleDescription.foreground': color('muted'),
        'peekViewEditor.background': color('code-bg'),
        'peekViewEditorGutter.background': color('code-bg'),
        'peekViewResult.background': color('bg'),
        'peekViewResult.fileForeground': color('text'),
        'peekViewResult.lineForeground': color('muted'),
        'peekViewResult.selectionBackground': color('selection'),
        'peekViewResult.selectionForeground': color('text'),
        'diffEditor.insertedTextBackground': `${color('success')}25`,
        'diffEditor.removedTextBackground': `${color('danger')}25`,
        'diffEditor.insertedLineBackground': `${color('success')}10`,
        'diffEditor.removedLineBackground': `${color('danger')}10`,
        'scrollbarSlider.background': color('scrollbar'),
        'scrollbarSlider.hoverBackground': color('scrollbar-hover'),
        'scrollbarSlider.activeBackground': color('scrollbar-hover'),
        'widget.shadow': color('shadow'),
      },
    })
    monaco.editor.setTheme(monacoThemeName)
  }
  apply()
  return editorTheme.subscribe(apply)
}
