import type { EditorBridge } from '@quajs/editor-core'
import { contextBridge, ipcRenderer } from 'electron'

const bridge: EditorBridge = {
  buildProject: (root, target) => ipcRenderer.invoke('editor:build-project', root, target),
  buildState: () => ipcRenderer.invoke('editor:build-state'),
  cancelBuild: () => ipcRenderer.invoke('editor:build-cancel'),
  revealBuild: () => ipcRenderer.invoke('editor:build-reveal'),
  onBuildState: listener => subscribe('editor:build-changed', listener),
  onAuthoringRequest: listener => subscribe('editor:authoring-request', listener),
  replyAuthoring: (id, result, error) => ipcRenderer.send('editor:authoring-reply', { id, result, error }),
  pluginPublishingState: root => ipcRenderer.invoke('editor:plugin-publishing-state', root),
  setPluginRegistry: url => ipcRenderer.invoke('editor:plugin-registry', url),
  pluginLogin: () => ipcRenderer.invoke('editor:plugin-login'),
  pollPluginLogin: () => ipcRenderer.invoke('editor:plugin-login-poll'),
  pluginLogout: () => ipcRenderer.invoke('editor:plugin-logout'),
  claimPlugin: root => ipcRenderer.invoke('editor:plugin-claim', root),
  preparePluginPublication: root => ipcRenderer.invoke('editor:plugin-prepare', root),
  publishPlugin: (root, artifact, otp) => ipcRenderer.invoke('editor:plugin-publish', root, artifact, otp),
  submitPlugin: root => ipcRenderer.invoke('editor:plugin-submit', root),
  cancelPluginPublication: () => ipcRenderer.invoke('editor:plugin-publish-cancel'),
  pluginMarketplace: (root, query) => ipcRenderer.invoke('editor:plugin-marketplace', root, query),
  pluginDetails: (root, name) => ipcRenderer.invoke('editor:plugin-details', root, name),
  setPluginCatalog: url => ipcRenderer.invoke('editor:plugin-catalog', url),
  installPlugin: (root, name, version) => ipcRenderer.invoke('editor:plugin-install', root, name, version),
  cancelPluginInstall: () => ipcRenderer.invoke('editor:plugin-cancel'),
  enablePlugin: (root, name, enabled) => ipcRenderer.invoke('editor:plugin-enable', root, name, enabled),
  onPluginInstall: listener => subscribe('editor:plugin-install-event', listener),
  navigationMenu: items => ipcRenderer.invoke('editor:navigation-menu', items),
  presentNovelWriter: (active, bounds) => ipcRenderer.invoke('editor:novel-writer-present', active, bounds),
  resizeNovelWriter: bounds => ipcRenderer.invoke('editor:novel-writer-bounds', bounds),
  onNovelWriterState: listener => subscribe('editor:novel-writer-state', listener),
  createTerminal: (root, cols, rows) => ipcRenderer.invoke('editor:terminal-create', root, cols, rows),
  writeTerminal: (id, data) => ipcRenderer.invoke('editor:terminal-write', id, data),
  resizeTerminal: (id, cols, rows) => ipcRenderer.invoke('editor:terminal-resize', id, cols, rows),
  acknowledgeTerminal: (id, sequence) => ipcRenderer.invoke('editor:terminal-ack', id, sequence),
  closeTerminal: id => ipcRenderer.invoke('editor:terminal-close', id),
  focusTerminal: focused => ipcRenderer.invoke('editor:terminal-focus', focused),
  onTerminalEvent: listener => subscribe('editor:terminal-event', listener),
  fileOperation: (root, operation) => ipcRenderer.invoke('editor:file-operation', root, operation),
  fileMenu: (root, path, canPaste) => ipcRenderer.invoke('editor:file-menu', root, path, canPaste),
  windowState: () => ipcRenderer.invoke('editor:window-state'),
  windowAction: (action, menuPosition) => ipcRenderer.invoke('editor:window-action', action, menuPosition),
  onWindowState: listener => subscribe('editor:window-changed', listener),
  openProject: () => ipcRenderer.invoke('editor:open'),
  chooseProjectLocation: () => ipcRenderer.invoke('editor:project-location'),
  createProject: request => ipcRenderer.invoke('editor:create', request),
  runtimeState: () => ipcRenderer.invoke('editor:runtime-state'),
  repairRuntime: root => ipcRenderer.invoke('editor:runtime-repair', root),
  cancelRuntime: () => ipcRenderer.invoke('editor:runtime-cancel'),
  onRuntimeState: listener => subscribe('editor:runtime-changed', listener),
  currentProject: () => ipcRenderer.invoke('editor:current'),
  refreshProject: () => ipcRenderer.invoke('editor:refresh'),
  onCommand: listener => subscribe('editor:command', listener),
  gitStatus: root => ipcRenderer.invoke('editor:git-status', root),
  onGitChange: listener => subscribe('editor:git-changed', listener),
  gitDiff: (root, path, staged) => ipcRenderer.invoke('editor:git-diff', root, path, staged),
  gitStage: (root, path, staged) => ipcRenderer.invoke('editor:git-stage', root, path, staged),
  gitCommit: (root, message) => ipcRenderer.invoke('editor:git-commit', root, message),
  gitBranches: root => ipcRenderer.invoke('editor:git-branches', root),
  gitSwitch: (root, branch, create) => ipcRenderer.invoke('editor:git-switch', root, branch, create),
  searchProject: request => ipcRenderer.invoke('editor:search', request),
  cancelSearch: () => ipcRenderer.invoke('editor:search-cancel'),
  assetUrl: (root, path, thumbnail) => ipcRenderer.invoke('editor:asset-url', root, path, thumbnail),
  imageMetadata: (root, path) => ipcRenderer.invoke('editor:image-metadata', root, path),
  revealFile: (root, path) => ipcRenderer.invoke('editor:reveal', root, path),
  importAssets: (root, directory) => ipcRenderer.invoke('editor:import-assets', root, directory),
  openAssetPreview: (root, path) => ipcRenderer.invoke('editor:asset-preview-open', root, path),
  onProjectChange: listener => subscribe('editor:project-changed', listener),
  readDocument: path => ipcRenderer.invoke('editor:read', path),
  saveDocument: document => ipcRenderer.invoke('editor:save', document),
  setDocumentDirty: dirty => ipcRenderer.invoke('editor:dirty', dirty),
  confirmDiscard: () => ipcRenderer.invoke('editor:confirm-discard'),
  analyzeDocument: (path, text) => ipcRenderer.invoke('editor:analyze', path, text),
  checkProject: root => ipcRenderer.invoke('editor:check-project', root),
  onProjectCheck: listener => subscribe('editor:project-check', listener),
  completeDocument: request => ipcRenderer.invoke('editor:complete', request),
  signatureDocument: request => ipcRenderer.invoke('editor:signature', request),
  hoverDocument: request => ipcRenderer.invoke('editor:hover', request),
  defineDocument: request => ipcRenderer.invoke('editor:define', request),
  formatDocument: (path, text, options) => ipcRenderer.invoke('editor:format', path, text, options),
  syncDocuments: (root, documents) => ipcRenderer.invoke('editor:sync-documents', root, documents),
  startPreview: target => ipcRenderer.invoke('editor:preview-start', target),
  reloadPreview: () => ipcRenderer.invoke('editor:preview-reload'),
  setPreviewMuted: muted => ipcRenderer.invoke('editor:preview-mute', muted),
  presentPreview: mode => ipcRenderer.invoke('editor:preview-present', mode),
  previewPerformance: (id, enabled) => ipcRenderer.invoke('editor:preview-performance', id, enabled),
  previewStorage: (id, request) => ipcRenderer.invoke('editor:preview-storage', id, request),
  inspectPreview: id => ipcRenderer.invoke('editor:preview-inspect', id),
  inspectPreviewNode: (id, node) => ipcRenderer.invoke('editor:preview-inspect-node', id, node),
  previewCommand: (sessionId, command) => ipcRenderer.invoke('editor:preview-command', sessionId, command),
  stopPreview: () => ipcRenderer.invoke('editor:preview-stop'),
  previewState: () => ipcRenderer.invoke('editor:preview-state'),
  setPreviewBounds: bounds => ipcRenderer.invoke('editor:preview-bounds', bounds),
  previewPointer: (sessionId, event) => ipcRenderer.invoke('editor:preview-pointer', sessionId, event),
  onPreviewState: listener => subscribe('editor:preview-changed', listener),
  onLog: listener => subscribe('editor:log', listener),
}
function subscribe<T>(channel: string, listener: (value: T) => void): () => void {
  const handler = (_event: unknown, value: T): void => listener(value)
  ipcRenderer.on(channel, handler)
  return () => ipcRenderer.removeListener(channel, handler)
}
contextBridge.exposeInMainWorld('quaEditor', bridge)
contextBridge.exposeInMainWorld('quaAssetPreview', {
  close: () => ipcRenderer.invoke('editor:asset-preview-close'),
})
