import type { TemplateResult } from 'lit'
import { html } from 'lit'
import { unsafeHTML } from 'lit/directives/unsafe-html.js'
import { icon } from '../../shared/icons'

export function navigationTemplate(): TemplateResult {
  return html`<nav id="activity-bar" class="activity-bar" role="tablist" aria-label="工作区视图" aria-orientation="vertical"><button id="activity-explorer" role="tab" aria-label="资源管理器" aria-controls="view-explorer" aria-selected="true"></button><button id="activity-search" role="tab" aria-label="搜索" aria-controls="view-search" aria-selected="false"></button><button id="activity-git" role="tab" aria-label="源代码管理" aria-controls="view-git" aria-selected="false"></button><button id="activity-story" role="tab" aria-label="故事大纲" aria-controls="view-story" aria-selected="false"></button><button id="activity-writer" role="tab" aria-label="Novel Writer" title="Novel Writer" aria-controls="novel-writer" aria-selected="false"></button><button id="activity-extensions" role="tab" aria-label="插件" title="插件" aria-controls="plugin-marketplace" aria-selected="false"></button><button id="settings-button" title="设置（⌘/Ctrl ,）" aria-label="编辑器设置">⚙</button></nav>
    <aside class="sidebar"><div class="sidebar-heading"><span id="sidebar-title"></span><div id="outline-actions" class="sidebar-actions" hidden><button id="outline-reveal" class="icon-button"></button><button id="outline-collapse" class="icon-button"></button></div><div id="explorer-actions"><button id="new-file" class="icon-button"></button><button id="new-folder" class="icon-button"></button><button id="reveal-document" class="icon-button"></button><button id="collapse-files" class="icon-button"></button></div></div><section id="view-explorer" class="sidebar-view" role="tabpanel" aria-labelledby="activity-explorer"><div id="file-filter" class="file-filter" hidden><div class="search-field"><input id="file-search" placeholder="筛选文件" aria-label="查找项目文件" aria-keyshortcuts="Control+F Meta+F"><button id="file-filter-close" class="icon-button" title="关闭文件筛选（Esc）" aria-label="关闭文件筛选">${unsafeHTML(icon('close'))}</button></div></div><nav id="files"></nav></section><section id="view-search" class="sidebar-view" role="tabpanel" aria-labelledby="activity-search" hidden></section><section id="view-git" class="sidebar-view" role="tabpanel" aria-labelledby="activity-git" hidden></section><section id="view-story" class="sidebar-view" role="tabpanel" aria-labelledby="activity-story" hidden><div class="outline-filter"><input id="outline-search" type="search" title="按标题、标识或路径筛选已保存文件的大纲" placeholder="筛选章节、节点、选项…" aria-label="筛选故事大纲" autocomplete="off" spellcheck="false"></div><nav id="story"></nav><p id="outline-message" class="outline-message" role="status" hidden></p></section></aside>
    <div id="sidebar-splitter" class="splitter vertical" role="separator" aria-label="调整侧栏宽度" aria-orientation="vertical" tabindex="0"></div>`
}
