// Global APIs (main exports)
export {
  activateRuntimePackage,
  autoSave,
  canRollback,
  canRollForward,
  clearChoices,
  createCheckpoint,
  createRollbackAnchor,
  deleteSaveSlot,
  dialogue,
  ensureLocalePacks,
  fixRollback,
  getAssetMetadata,
  getAssets,
  getCheckpoint,
  getCurrentSceneName,
  getCurrentStepId,
  getFlowControlState,
  getLocale,
  getPipeline,
  getPluginProjection,
  getRollbackConfig,
  getRollbackTargets,
  getRuntimePackages,
  getStore,
  getStoryPoint,
  getViewState,
  hideDialogue,
  initEngine,
  jumpTo,
  jumpToChoice,
  listSaveSlots,
  loadFromSlot,
  loadRuntimePackage,
  loadScene,
  quickLoad,
  quickSave,
  registerRollbackStore,
  registerScene,
  registerScriptModule,
  registerStoryTargetResolver,
  reportError,
  resetFlowControlPolicy,
  resolveStoryAssetRef,
  resolveStoryTarget,
  rewind,
  rollback,
  rollForward,
  runScriptModule,
  runScriptModuleFrom,
  saveToSlot,
  setDialogueOptions,
  setFlowControlMode,
  setFlowControlOptions,
  setFlowControlPolicy,
  setLayoutProjection,
  setLocale,
  setPluginProjection,
  setRendererOptions,
  setRollbackConfig,
  setStoryPoint,
  showChoices,
  showDialogue,
  startAuto,
  startFastForward,
  startSkip,
  stopAuto,
  stopFastForward,
  stopSkip,
  t,
  translate,
  unloadRuntimePackage,
  unregisterRollbackStore,
  waitFor,
} from './api/global'

// Core Engine
export { QuaEngine } from './core/engine'

export {
  assertSerializableSceneState,
  checkpoint,
  defineChoice,
  image,
  isChoiceTarget,
  label,
  node,
  packageNode,
  scene,
  script,
} from './core/story-targets'
export { resolveQuaText } from './core/text'
export type { QuaTextPart, QuaTranslate } from './core/text'
// Types
export { Scene } from './core/types'
export type {
  BackgroundIntent,
  CharacterIntent,
  CheckpointChoiceTarget,
  ChoiceDefinition,
  ChoiceDefinitionOptions,
  ChoiceIntent,
  ChoiceJumpOptions,
  ChoicePresentation,
  ChoiceTarget,
  ChoiceTargetBase,
  ChoiceUnavailablePolicy,
  CreateCheckpointOptions,
  DialogueIntent,
  DialogueOptions,
  DialogueTypewriterInput,
  EndGameOptions,
  EngineCheckpoint,
  EngineCheckpointKind,
  EngineConfig,
  EngineEventMap,
  EngineGameOverState,
  EngineProjectInfo,
  EngineReportErrorOptions,
  EnsureLocalePacksOptions,
  FlowControlOptions,
  FlowControlRuntimeOptions,
  GameSaveData,
  GameStep,
  GameStepFactory,
  GameStepList,
  GameStepScope,
  GameStepSource,
  JsonSerializable,
  JsonSerializableRecord,
  JumpContext,
  JumpOptions,
  JumpTarget,
  LabelChoiceTarget,
  LoadSlotOptions,
  NodeChoiceTarget,
  OptionalGameStepFactory,
  PackageNodeChoiceTarget,
  QuaEngineInterface,
  ResolvedStoryAsset,
  ResolvedStoryJump,
  RollbackAnchor,
  RollbackAnchorReason,
  RollbackBoundaryConfig,
  RollbackBoundaryMode,
  RollbackCheckpointConfig,
  RollbackConfig,
  RollbackConfigPatch,
  RollbackContext,
  RollbackEntry,
  RollbackForwardConfig,
  RollbackJournal,
  RollbackNavigationOptions,
  RollbackRecordedInput,
  RollbackSaveConfig,
  RollbackSegment,
  RollbackSnapshotSet,
  RollbackTarget,
  RollbackTargetInfo,
  RuntimeLoadedMigrationModule,
  RuntimeLoadedPluginModule,
  RuntimeLoadedSceneModule,
  RuntimeLoadedScriptModule,
  RuntimeLocalePackManifest,
  RuntimeLocalePackRegistryResolveContext,
  RuntimeLocalePackTargetManifest,
  RuntimeModuleLoadContext,
  RuntimeModuleLoader,
  RuntimePackageContext,
  RuntimePackageLoadOptions,
  RuntimePackageManifest,
  RuntimePackagePluginManifest,
  RuntimePackageRegistry,
  RuntimePackageRegistryEntry,
  RuntimePackageRegistryResolveContext,
  RuntimePackageRegistryResolveStoryTargetContext,
  RuntimePackageSceneManifest,
  RuntimePackageScriptManifest,
  RuntimePackageScriptVariantManifest,
  RuntimePackageState,
  RuntimePackageStateRecord,
  RuntimePackageStoreMigrationManifest,
  RuntimePackageStoryGraphDeltaManifest,
  RuntimePackageTrustContext,
  RuntimePackageUnloadOptions,
  RuntimeScriptModuleRecord,
  RuntimeScriptModuleRunFromOptions,
  RuntimeScriptModuleRunOptions,
  RuntimeStoreMigrationContext,
  RuntimeStoreMigrationHandler,
  RuntimeTrustPolicy,
  SaveSlot,
  SceneChoiceTarget,
  SceneEnterContext,
  SceneFactory,
  ScriptChoiceTarget,
  SetLocaleOptions,
  SlotMetadata,
  StepContext,
  StoryAssetRef,
  StoryPoint,
  StoryTargetResolveContext,
  StoryTargetResolver,
  TranslateInput,
  TranslateOptions,
  UsePluginOptions,
  ViewPluginProjectionMap,
} from './core/types'
// Events
export {
  emitLogicToRender,
  emitRenderToLogic,
  isRichTextDocument,
  LogicToRenderEvents,
  onLogicToRender,
  onRenderToLogic,
  RenderToLogicEvents,
  richTextToPlainText,
  waitForPipelineEvent,
} from './events/events'
export type {
  ActiveAnimationProjection,
  AnimationFillMode,
  AnimationInterpolation,
  AnimationKeyframeProjection,
  AnimationPlaybackState,
  AnimationTime,
  AnimationTimingFunction,
  BackgroundBlendMode,
  BackgroundCompositionProjection,
  BackgroundFilterProjection,
  BackgroundFit,
  BackgroundLayerAssetType,
  BackgroundMaskProjection,
  BackgroundMode,
  BackgroundSetPayload,
  BuiltinOverlayStack,
  DialogueAvatarProjection,
  DialogueShowPayload,
  DialogueTypewriterProjection,
  DialogueTypewriterSoundProjection,
  EngineEvents,
  FlowControlAdvanceProjection,
  FlowControlControlsProjection,
  FlowControlMode,
  FlowControlPolicy,
  FlowControlProjectionInput,
  FlowControlSetModePayload,
  FlowControlSkipMode,
  FlowControlTimingProjection,
  GameOverPayload,
  RendererInputCommand,
  RendererInputCommandPayload,
  RendererInputDevice,
  RendererTextInputPayload,
  RendererTextInputPhase,
  ResolvedAnimationTrackProjection,
  ResolvedFlowControlPolicy,
  ResolvedOverlayStackPlacement,
  ResolveOverlayStackPlacementOptions,
  RichTextBlockProjection,
  RichTextContent,
  RichTextDocumentProjection,
  RichTextSpanProjection,
  RichTextStyleProjection,
  RuntimePackagePluginPayload,
  RuntimePackageUnloadPayload,
  SceneChangePayload,
  SceneInitPayload,
  SceneTransitionIntent,
  SceneTransitionType,
  UserChoiceSelectPayload,
  UserClickPayload,
  ViewBackgroundLayerProjection,
  ViewBackgroundProjection,
  ViewFlowControlProjection,
  ViewLayoutInput,
  ViewLayoutOrientation,
  ViewLayoutPreset,
  ViewLayoutProjection,
  ViewLayoutScaleMode,
  RendererUiIntentPayload,
  ViewOverlayStackPlacement,
  ViewUiOverlayProjection,
  ViewVideoBackgroundProjection,
} from './events/events'
export {
  compareOverlayStackPlacement,
  compareResolvedOverlayStackPlacement,
  compareUiOverlayStackPlacement,
  createFlowControlProjection,
  createViewLayoutProjection,
  DEFAULT_OVERLAY_STACK_PRIORITIES,
  DEFAULT_UI_OVERLAY_Z_INDEXES,
  OVERLAY_STACK_Z_INDEX_STRIDE,
  QUA_DEFAULT_FLOW_CONTROL_POLICY,
  QUA_DEFAULT_FLOW_CONTROL_TIMINGS,
  QUA_LANDSCAPE_LAYOUT,
  QUA_LAYOUT_PRESETS,
  QUA_PORTRAIT_LAYOUT,
  resolveActiveUiSceneProjection,
  resolveOverlayStackPlacement,
  resolveUiOverlayStackPlacement,
} from './events/events'

// Managers
export { GameManager } from './managers/game-manager'
export { SceneManager } from './managers/scene-manager'

export type { SceneTransition, SceneTransitionOptions } from './managers/scene-manager'

// Plugin System (organized structure)
export {
  BaseEnginePlugin,
  defineAPIFunction,
  defineDecorator,
  getDiscoveredDecoratorMappings,
  getPluginDiscovery,
  getPluginRegistry,
  PluginAPIRegistry,
  PluginDiscovery,
  PluginFramework,
} from './plugins'
export type {
  DecoratorMapping,
  EngineContext,
  EnginePlugin,
  PluginAPIFunction,
  PluginAPIRegistration,
  PluginConstructor,
  PluginConstructorOptions,
} from './plugins'
export {
  getUiOverlayHostProjection,
  releaseUiOverlayHostWithEngine,
  retainUiOverlayHostWithEngine,
  UI_OVERLAY_HOST_SCENE_ID,
  UiOverlayPlugin,
} from './plugins/ui-overlay-plugin'
export type {
  UiOverlayHostReleaseOptions,
  UiOverlayHostRetainOptions,
  UiOverlayPluginOptions,
} from './plugins/ui-overlay-plugin'
