export const shortcuts = [
  ['保存', '⌘ / Ctrl S'],
  ['全部保存', '⌘ / Ctrl Shift S'],
  ['关闭文档', '⌘ / Ctrl W'],
  ['切换文档', 'Ctrl Tab'],
  ['查找', '⌘ / Ctrl F'],
  ['文档替换', '⌘ / Ctrl H'],
  ['撤销', '⌘ / Ctrl Z'],
  ['重做', '⌘ / Ctrl Shift Z'],
  ['格式化文档', 'Shift Alt F'],
  ['转到定义', 'F12'],
  ['快速打开文件', '⌘ / Ctrl P'],
  ['全项目搜索', '⌘ / Ctrl Shift F'],
  ['编辑器设置', '⌘ / Ctrl ,'],
  ['切换调试面板', '⌘ / Ctrl J'],
  ['切换终端', 'Ctrl `'],
  ['新建终端', 'Ctrl Shift `'],
  ['运行预览', 'F5'],
  ['停止预览', 'Shift F5'],
  ['单步预览', 'F10'],
  ['预览光标所在步骤', '⌘ / Ctrl Alt Enter'],
] as const
