import assert from 'node:assert/strict'
import { execFile } from 'node:child_process'
import { mkdir, mkdtemp, readFile, realpath, rm, writeFile } from 'node:fs/promises'
import { createRequire } from 'node:module'
import { tmpdir } from 'node:os'
import { join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { promisify } from 'node:util'
import { _electron } from 'playwright'

const root = fileURLToPath(new URL('../../../../', import.meta.url))
const editorRoot = resolve(root, 'packages/editor/electron')
const require = createRequire(join(editorRoot, 'package.json'))
const temporary = await realpath(await mkdtemp(join(tmpdir(), 'qua-git-smoke-')))
const projectRoot = join(temporary, 'story')
const secondRoot = join(temporary, 'second')
const artifacts = resolve(root, '.codex-tmp/editor-git-smoke')
await mkdir(artifacts, { recursive: true })
for (const project of [projectRoot, secondRoot]) {
  await mkdir(project)
  await writeFile(join(project, 'qua.project.json'), JSON.stringify({ schemaVersion: 1, name: project === projectRoot ? '剧情项目' : 'Second project', bundleId: 'dev.qua.git', icons: { favicon: 'icon.png' }, targets: { web: { enabled: true } } }))
  await writeFile(join(project, 'package.json'), JSON.stringify({ name: 'git-fixture', scripts: { 'dev:web': 'vite' } }))
}
const execute = promisify(execFile)
const git = async (...args) => (await execute('git', args, { cwd: projectRoot })).stdout
await git('init', '-b', 'main')
await git('config', 'user.name', 'Editor Test')
await git('config', 'user.email', 'editor@example.invalid')
await git('config', 'commit.gpgsign', 'false')
await git('config', 'core.hooksPath', join(projectRoot, '.git', 'empty-hooks'))
await writeFile(join(projectRoot, 'scene.qs'), 'Mara: 原来的台词。\n')
await git('add', '.')
await git('commit', '-m', 'chore(test): initialize')
await writeFile(join(projectRoot, 'scene.qs'), 'Mara: 保存到磁盘的台词。\n')
const env = { ...process.env }
delete env.ELECTRON_RUN_AS_NODE
let application
let page
try {
  application = await _electron.launch({ executablePath: require('electron'), args: [editorRoot, '--project', projectRoot, `--user-data-dir=${join(temporary, 'profile')}`], env, timeout: 60000 })
  page = await application.firstWindow()
  const errors = []
  page.on('pageerror', error => errors.push(error.message))
  await page.locator('.dock-separator[data-split-id="main"]').dblclick()
  await page.locator('#tab-console').click()
  await page.locator('#files[data-project-name="剧情项目"]').waitFor()
  await page.locator('#git-branch').filter({ hasText: 'main*' }).waitFor()
  assert.equal(await page.locator('#project-name, #open-project, #refresh-project, #tree-file-count').count(), 0)
  assert.match((await page.locator('.titlebar').textContent()).trim(), /^QUA \/ EDITOR/)
  assert.equal(await page.locator('#workbench-views').isVisible(), true)
  await page.locator('#files [data-path="scene.qs"]').click()
  await page.locator('#document-name').filter({ hasText: 'scene.qs' }).waitFor()
  await page.locator('#editor .view-lines').filter({ hasText: '保存到磁盘的台词' }).waitFor()
  await page.keyboard.press(process.platform === 'darwin' ? 'Meta+ArrowDown' : 'Control+End')
  await page.keyboard.insertText('Mara: 未保存的草稿。\n')
  await page.locator('.document-tab.active .tab-close').filter({ hasText: '●' }).waitFor()
  await page.locator('#activity-git').click()
  await page.locator('#view-git').waitFor()
  const working = page.locator('.git-change[data-path="scene.qs"][data-staged="false"]')
  await working.locator('.git-file').click()
  await page.locator('#git-diff-title').filter({ hasText: '暂存区 ↔ 工作树' }).waitFor()
  await page.locator('#git-diff .view-lines').filter({ hasText: '保存到磁盘的台词' }).waitFor()
  assert.ok(!(await page.locator('#git-diff').textContent()).includes('未保存的草稿'))
  await page.screenshot({ path: join(artifacts, 'git-diff.png') })
  await working.getByRole('button', { name: '暂存更改', exact: true }).click()
  const staged = page.locator('.git-change[data-path="scene.qs"][data-staged="true"]')
  await staged.waitFor()
  await staged.getByRole('button', { name: '取消暂存', exact: true }).click()
  await working.waitFor()
  await working.getByRole('button', { name: '暂存更改', exact: true }).click()
  await staged.waitFor()
  await page.locator('#git-commit-message').fill('feat(story): revise dialogue')
  await page.locator('#git-commit').click()
  await page.locator('#git-summary').filter({ hasText: '0 个文件变更' }).waitFor()
  assert.equal((await git('log', '-1', '--format=%s')).trim(), 'feat(story): revise dialogue')
  assert.equal(await git('show', 'HEAD:scene.qs'), 'Mara: 保存到磁盘的台词。\n')
  await application.evaluate(({ dialog }) => {
    dialog.showMessageBox = async (window, options) => {
      globalThis.lastBranchPrompt = options
      return { response: 2, checkboxChecked: false }
    }
  })
  await page.locator('#git-branch').click()
  await page.locator('#git-new-branch').fill('feature/dialogue')
  await page.locator('#git-create-branch').click()
  await page.locator('#git-message').filter({ hasText: '已取消切换分支' }).waitFor()
  const prompt = await application.evaluate(() => globalThis.lastBranchPrompt)
  assert.deepEqual(prompt.buttons, ['保存全部并切换', '保留草稿并切换', '取消'])
  assert.equal(prompt.type, 'question')
  assert.equal(await page.locator('#git-message').evaluate(element => element.classList.contains('error')), false)
  assert.equal((await git('branch', '--show-current')).trim(), 'main')
  assert.equal((await git('branch', '--list', 'feature/dialogue')).trim(), '')
  await page.locator('.document-tab[data-kind="file"][data-path="scene.qs"] [role="tab"]').click()
  await page.locator('#editor .view-lines').filter({ hasText: '未保存的草稿' }).waitFor()
  await application.evaluate(({ dialog }) => {
    dialog.showMessageBox = async () => ({ response: 1, checkboxChecked: false })
  })
  await page.locator('#git-create-branch').click()
  await page.locator('#git-branch').filter({ hasText: 'feature/dialogue' }).waitFor()
  assert.equal(await page.locator('.document-tab.active .tab-close').textContent(), '●')
  assert.ok(!(await readFile(join(projectRoot, 'scene.qs'), 'utf8')).includes('未保存的草稿'))
  await page.locator('#git-choose-branch').click()
  await page.locator('#git-branches').selectOption('main')
  await application.evaluate(({ dialog }) => {
    dialog.showMessageBox = async () => ({ response: 0, checkboxChecked: false })
  })
  await page.locator('#git-switch').click()
  await page.locator('#git-branch').filter({ hasText: /^main\*/ }).waitFor()
  await page.locator('.document-tab.active .tab-close').filter({ hasText: '×' }).waitFor()
  await page.waitForFunction(() => !document.querySelector('#git-choose-branch').disabled)
  assert.match(await readFile(join(projectRoot, 'scene.qs'), 'utf8'), /未保存的草稿/)
  await git('switch', 'feature/dialogue')
  await page.bringToFront()
  await application.evaluate(({ app, BrowserWindow }) => {
    app.focus({ steal: true })
    BrowserWindow.getAllWindows()[0].focus()
  })
  process.stdout.write(`External Git refresh focus: ${await application.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows()[0].isFocused())}\n`)
  await page.locator('#git-branch').filter({ hasText: 'feature/dialogue' }).waitFor({ timeout: 15000 })
  await page.screenshot({ path: join(artifacts, 'git-branch.png') })
  // Directory tree, combined index/worktree status, filter and bounded DOM.
  await mkdir(join(projectRoot, 'src/scenes'), { recursive: true })
  await mkdir(join(projectRoot, 'assets/images'), { recursive: true })
  await writeFile(join(projectRoot, 'src/scenes/序章.qs'), 'Mara: staged\n')
  await git('add', 'src/scenes/序章.qs')
  await writeFile(join(projectRoot, 'src/scenes/序章.qs'), 'Mara: working\n')
  await Promise.all(Array.from({ length: 240 }, (_, index) => writeFile(join(projectRoot, `assets/images/item-${index}.txt`), 'fixture')))
  await page.locator('#git-refresh').click()
  if (await page.locator('#git-view-mode').getAttribute('data-mode') === 'list')
    await page.locator('#git-view-mode').click()
  await page.locator('#git-filter').fill('序章')
  const nestedWorking = page.locator('.git-change[data-path="src/scenes/序章.qs"][data-staged="false"]')
  const nestedStaged = page.locator('.git-change[data-path="src/scenes/序章.qs"][data-staged="true"]')
  await nestedWorking.waitFor()
  await nestedStaged.waitFor()
  assert.equal(await nestedWorking.locator('.git-status-letter').textContent(), 'M')
  assert.equal(await nestedStaged.locator('.git-status-letter').textContent(), 'A')
  assert.equal(await nestedWorking.getAttribute('aria-level'), '4')
  await nestedWorking.locator('.git-file').click()
  await page.locator('#git-diff-title').filter({ hasText: 'src/scenes/序章.qs' }).waitFor()
  await page.locator('#git-filter').fill('')
  await page.locator('.git-folder[data-path="assets"]').waitFor()
  await page.screenshot({ path: join(artifacts, 'git-tree.png') })
  assert.ok(await page.locator('#git-files [role="treeitem"]').count() < 80)
  await page.locator('#git-collapse').click()
  assert.equal(await page.locator('#git-files [role="treeitem"]').count(), 2)
  await page.keyboard.press('Home')
  await page.keyboard.press('ArrowRight')
  await page.keyboard.press('ArrowRight')
  await page.keyboard.press('ArrowRight')
  await page.locator('.git-folder[data-path="src/scenes"][data-staged="true"]').waitFor()
  await page.keyboard.press('ArrowRight')
  await page.keyboard.press('ArrowRight')
  await nestedStaged.waitFor()
  await page.keyboard.press('ArrowRight')
  await page.keyboard.press('Enter')
  await page.locator('#git-diff-title').filter({ hasText: 'HEAD ↔ 暂存区' }).waitFor()
  await page.locator('#git-filter').fill('序章')
  assert.equal(await page.locator('#git-filter').inputValue(), '序章')
  await nestedWorking.waitFor()
  await page.locator('#git-view-mode').click()
  await nestedWorking.waitFor()
  assert.equal(await nestedWorking.getAttribute('aria-level'), '2')
  assert.equal(await page.locator('#git-files .git-folder').count(), 0)
  await page.locator('#git-view-mode').click()
  await page.locator('#git-filter').fill('')

  await git('add', 'scene.qs')
  await git('commit', '-m', 'chore(test): save fixture state')
  await git('switch', '-c', 'conflict-target')
  await writeFile(join(projectRoot, 'scene.qs'), 'Mara: target branch\n')
  await git('commit', '-am', 'chore(test): conflicting target')
  await git('switch', 'feature/dialogue')
  await writeFile(join(projectRoot, 'scene.qs'), 'Mara: local disk changes\n')
  await page.locator('#git-refresh').click()
  await page.locator('#git-branch').filter({ hasText: 'feature/dialogue' }).waitFor()
  await page.locator('#git-choose-branch').click()
  await page.locator('#git-branches').selectOption('conflict-target')
  await page.locator('#git-switch').click()
  await page.locator('#git-message.warning').filter({ hasText: '切换会覆盖本地更改' }).waitFor()
  assert.equal(await page.locator('#git-message').evaluate(element => element.classList.contains('error')), false)
  assert.ok(!(await page.locator('#git-message').textContent()).includes('Error invoking'))
  assert.equal((await git('branch', '--show-current')).trim(), 'feature/dialogue')
  assert.equal(await readFile(join(projectRoot, 'scene.qs'), 'utf8'), 'Mara: local disk changes\n')
  await page.screenshot({ path: join(artifacts, 'git-switch-warning.png') })
  await page.locator('.document-tab[data-kind="file"][data-path="scene.qs"] [role="tab"]').click()
  await page.locator('#editor .view-lines').filter({ hasText: 'local disk changes' }).waitFor()
  await application.evaluate(({ Menu }) => Menu.getApplicationMenu().getMenuItemById('refresh-project').click())
  await page.locator('#status').filter({ hasText: '项目已刷新' }).waitFor()
  // A draft stays in its model even when checkout changes the same disk file.
  const base = await git('show', 'HEAD:scene.qs')
  await writeFile(join(projectRoot, 'scene.qs'), base)
  await page.locator('#editor .view-lines').filter({ hasText: '未保存的草稿' }).waitFor()
  await page.locator('#editor .view-lines').click()
  await page.keyboard.press(process.platform === 'darwin' ? 'Meta+ArrowDown' : 'Control+End')
  await page.keyboard.insertText('Mara: 跨分支保留的草稿。\n')
  await page.locator('.document-tab.active .tab-close').filter({ hasText: '●' }).waitFor()
  await application.evaluate(({ dialog }) => {
    dialog.showMessageBox = async () => ({ response: 1, checkboxChecked: false })
  })
  await page.locator('#git-switch').click()
  await page.locator('#git-branch').filter({ hasText: 'conflict-target' }).waitFor()
  await page.locator('#editor .view-lines').filter({ hasText: '跨分支保留的草稿' }).waitFor()
  await page.locator('#disk-change').waitFor()
  assert.equal(await page.locator('.document-tab.active .tab-close').textContent(), '●')
  await page.locator('#save').click()
  await page.locator('#status.error').filter({ hasText: '文件已被外部修改' }).waitFor()
  assert.equal(await readFile(join(projectRoot, 'scene.qs'), 'utf8'), 'Mara: target branch\n')
  await page.screenshot({ path: join(artifacts, 'git-draft-conflict.png') })
  await application.evaluate(({ dialog, Menu }, root) => {
    dialog.showOpenDialog = async () => ({ canceled: false, filePaths: [root] })
    Menu.getApplicationMenu().getMenuItemById('open-project').click()
  }, secondRoot)
  await page.locator('#git-branch').filter({ hasText: '未使用 Git' }).waitFor()
  assert.equal(await page.locator('.git-change').count(), 0)
  assert.equal(await page.locator('#git-diff').isVisible(), false)
  assert.deepEqual(errors, [])
  process.stdout.write('Git: branch status, clean titlebar, disk/index diffs, stage/unstage, local commit, cancel/save/keep-draft branch switching, changed-file draft preservation, grouped tree/list views, folder keyboard navigation, status colors, filtering and virtualization, external Git refresh and native menu project replacement passed\n')
}
catch (error) {
  await page?.screenshot({ path: join(artifacts, 'failure.png') }).catch(() => {})
  throw error
}
finally {
  await application?.evaluate(({ dialog }) => {
    dialog.showMessageBox = async () => ({ response: 1, checkboxChecked: false })
  }).catch(() => {})
  await application?.close()
  await rm(temporary, { recursive: true, force: true })
}
